```{r}
crop_summary <- function(growth_probability, 
                         yield, 
                         stages){
  paste0(c(
    sprintf("* Growth Stages: %s", stages), 
    sprintf("* $\\Pr(Growth|RTick) = %s$",  growth_probability), 
    sprintf("* Yield: %s", yield), 
    
    # Time To Growth ------------------------------------------------
    "* Time To Growth (TTG)", 
    sprintf("    + $TTG_M: %s$", 
            time_to_growth(growth_probability)), 
    sprintf("    + $TTG_\\mu: %s$", 
            time_to_growth(growth_probability, 
                           method = "mean")), 
    sprintf("    + $TTG_{0.05}: %s$", 
            time_to_growth(growth_probability,
                           p = 0.05,
                           method = "quantile")), 
    sprintf("    + $TTG_{0.10}: %s$", 
            time_to_growth(growth_probability,
                           p = 0.10,
                           method = "quantile")), 
    sprintf("    + $TTG_{0.90}: %s$", 
            time_to_growth(growth_probability,
                           p = 0.90,
                           method = "quantile")), 
    sprintf("    + $TTG_{0.95}: %s$", 
            time_to_growth(growth_probability,
                           p = 0.95,
                           method = "quantile")), 
    
    # Time To Maturity ----------------------------------------------
    "* Time To Maturity (TTM)", 
    sprintf("    + $TTM_M: %s$", 
            time_to_maturity(growth_probability, 
                             stages = stages)), 
    sprintf("    + $TTM_\\mu: %s$", 
            time_to_maturity(growth_probability, 
                             stages = stages,
                             method = "mean")), 
    sprintf("    + $TTM_{0.05}: %s$", 
            time_to_maturity(growth_probability,
                             stages = stages,
                             p = 0.05,
                             method = "quantile")), 
    sprintf("    + $TTM_{0.10}: %s$", 
            time_to_maturity(growth_probability,
                             stages = stages,
                             p = 0.10,
                             method = "quantile")), 
    sprintf("    + $TTM_{0.90}: %s$", 
            time_to_maturity(growth_probability,
                             stages = stages,
                             p = 0.90,
                             method = "quantile")), 
    sprintf("    + $TTM_{0.95}: %s$", 
            time_to_maturity(growth_probability,
                             stages = stages,
                             p = 0.95,
                             method = "quantile")),
    
    # Expected Crop Output ------------------------------------------
    "* Expected Crop Output (ECO)", 
    sprintf("    + $ECO_M: %s$", 
            expected_crop_output(yield = yield, 
                                 growth_probability, 
                                 stages = stages)), 
    sprintf("    + $ECO_\\mu: %s$", 
            expected_crop_output(yield = yield, 
                                 growth_probability, 
                                 stages = stages,
                                 method = "mean")) 
  ), collapse = "\n")
}
```

```{r}
smelt_summary <- function(total_smelt, 
                          self_smelt, 
                          craft_consumption, 
                          yield, 
                          growth_probability, 
                          stages, 
                          label = ""){
  paste(c(
    sprintf("* Smelting Metrics (%s)", label), 
    sprintf("    + $NSG_M: %s$", 
            net_smelting_gain(total_smelt, 
                              self_smelt, 
                              craft_consumption)), 
    sprintf("    + $PFI_M: %s$", 
            perpetual_furnace_index(total_smelt, 
                                    self_smelt, 
                                    craft_consumption, 
                                    yield, 
                                    growth_probability, 
                                    stages))
  ), collapse = "\n")
}
```