# Time to Growth

The Time To Growth ($TTG$) is the duration of time until a crop advances a growth stage measured in minutes. The probability of growth is the intersection of the independent events of a random tick being assigned to the block and growth occurring. For a single block, the probability of a growth event is 

$$
\Pr(RTick \cap Growth) = \Pr(RTick) \cdot \Pr(Growth | RTick)
$$

As farms increase in size, however, the probability of a growth event changes. It must also be considered that a farm with more than one block assigned may have more than one growth event within a single tick. This means the probability function must account for both the number of blocks assigned a random tick and the number of ticked blocks that experience growth. 

It was demonstrated earlier that the number of blocks in the farm receiving a random tick has a hypergeometric probability distribution. Suppose, then, that $F_r$ blocks of farm land receive a random tick. Each has an independent probability of advancing a growth stage $\Pr(Growth|RTick)$, and the number of those blocks that advance a stage can be modeled using a _Binomial_ distribution with $n = F_r$ and $p = \Pr(Growth|RTick)$.

The calculation is further complicated by the fact that both the number of the number of farm blocks receiving a random tick and the number of growth events among those blocks are both random variables. There may be between zero and three farm blocks that receive a random tick, and between zero and three blocks that experience growth, creating sixteen events in the joint sample space. Applying the Law of Total Probability, the probability distribution function for $G$ growth events for $F_r$ farm blocks receiving a random tick is (using $rts$ as the random tick speed and $B$ as the number of blocks in a subchunk):

$$\begin{aligned}
\Pr(G = g, F_r = f | F)
  &= \frac{HyperG(F, f, B, rts) \cdot Binom(g; n = f, p = \Pr(Growth|RTick))}
          {\sum\limits_{i_f}^{F_r} \sum\limits_{i_g}^g 
            HyperG(F, i_f, B, rts) \cdot 
            Binom(i_g; n = i_f, p = \Pr(Growth|RTick))} \\
  &= \frac{\frac{{F \choose f}{B-F \choose rts - f}}{{B \choose rts}} \cdot 
                 {f \choose g} \cdot \Pr(Growth|RTick) ^ g \cdot (1 - \Pr(Growth|RTick)) ^ {f-g}}
          {\sum\limits_{i_f}^{F_r} \sum\limits_{i_g}^g 
              \frac{{F \choose i_f}{B-F \choose rts - i_f}}{{B \choose rts}} \cdot 
              {i_f \choose i_g} \cdot \Pr(Growth|RTick) ^ {i_g} \cdot (1 - \Pr(Growth|RTick)) ^ {i_f-i_g}}
\end{aligned}$$